version: '3'

services:
  setup-gnoland:
    image: golang:1.20-bookworm
    working_dir: /app
    entrypoint: make 0_setup_gnokey 1_setup_gnoland
    volumes:
      - goroot:/go:rw
      - gnoconfig:/root/.config/gno
      - .:/app

  setup-realm:
    image: golang:1.20-bookworm
    working_dir: /app
    entrypoint: make 5_deploy_realm
    links:
      - gnoland
    depends_on:
      gnoland:
        condition: service_healthy
    environment:
      - GNOLAND_REMOTE=gnoland:2323
    volumes:
      - goroot:/go:rw
      - gnoconfig:/root/.config/gno
      - .:/app

  gnoland:
    image: golang:1.20-bookworm
    depends_on:
      setup-gnoland:
        condition: service_completed_successfully
    working_dir: /app
    healthcheck:
      test: [
      "CMD",
      "go", "run",
      "github.com/gnolang/gno/gno.land/cmd/gnokey", "query", "auth/accounts/g185rxzrsc0j69amfsl255k2fxtlnt3cw8f3eu6h" # query deploy key
      ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 3s
    entrypoint: [
    "sh", "-c",
    "apt-get update && apt-get install -y socat && socat TCP-LISTEN:2323,fork,reuseaddr TCP:127.0.0.1:26657 & make 2_run_gnoland"
    ]
    volumes:
      - goroot:/go
      - gnoconfig:/root/.config/gno
      - .:/app
    ports:
      - 26657:2323

  faucet:
    image: golang:1.20-bookworm
    links:
      - gnoland
    # depends_on:
    #   setup-gnoland:
    #     condition: service_completed_successfully
    depends_on:
      gnoland:
        condition: service_healthy
    environment:
      - GNOLAND_REMOTE=gnoland:2323
    working_dir: /app
    entrypoint: make 3_run_faucet
    volumes:
      - goroot:/go
      - gnoconfig:/root/.config/gno
      - .:/app
    ports:
      - 8545:8545

  webui:
    working_dir: /app
    depends_on:
      - gnoland
      - faucet
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: ["sh", "-c", "socat TCP-LISTEN:2323,fork,reuseaddr TCP:127.0.0.1:1313 & make 4_run_web"]
    volumes:
      - .:/app
    ports:
      - "1313:2323"

volumes:
  goroot:
  gnoconfig:
